[svt]
title = "SVT Nyheter"
url = "https://www.svt.se"
entrySelector = "article.nyh_teaser"
linkSelector = "a.nyh_teaser__link"
titleSelector = ".nyh_teaser__heading-title"
contentSelector = ".nyh_teaser__vignette"
imageSelector = ".pic__img"

[expressen]
title = "Expressen"
url = "https://www.expressen.se"
entrySelector = "main#content a[href*='/nyheter/']"
linkSelector = "*"
titleSelector = "h2"
contentSelector = "p"
imageSelector = "img"

[svd]
title = "Svenska Dagbladet"
url = "https://www.svd.se"
entrySelector = ".Teaser-link"
linkSelector = "*"
titleSelector = ".Teaser-heading"
contentSelector = "p"
imageSelector = "img"

[dn]
title = "Dagens Nyheter"
url = "https://www.dn.se"
entrySelector = ".ds-teaser"
linkSelector = "*"
titleSelector = ".ds-teaser__title"
contentSelector = ".ds-teaser__text"
imageSelector = ".ds-teaser-image img"
