[svt]
title = "SVT Nyheter"
url = "https://www.svt.se"
entrySelector = "article.nyh_teaser"
linkSelector = "a.nyh_teaser__link"
titleSelector = ".nyh_teaser__heading-title"
contentSelector = [".pic__img", ".nyh_teaser__vignette"]

[expressen]
title = "Expressen"
url = "https://www.expressen.se"
entrySelector = "main#content a[href*='/nyheter/']"
linkSelector = "*"
titleSelector = "h2"
contentSelector = ["picture", "p"]

[svd]
title = "Svenska Dagbladet"
url = "https://www.svd.se"
entrySelector = ".Teaser-link"
linkSelector = "*"
titleSelector = ".Teaser-heading"
contentSelector = ["picture", "p"]

[dn]
title = "Dagens Nyheter"
url = "https://www.dn.se"
entrySelector = ".ds-teaser"
linkSelector = "*"
titleSelector = ".ds-teaser__title"
contentSelector = [".ds-teaser-image img", ".ds-teaser__text"]
